name: trigger other workflow

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:

      - name: trigger other repo
        run: curl -X POST -H "Authorization:Bearer ${{secrets.PAT_TOKEN }}" -H "X-GitHub-Api-Version:2022-11-28" https://api.github.com/repos/shinysht/testworkflow/actions/workflows/update.yml/dispatches --data '{"ref":"main"}'